### ISSUE TITLE
Twig_Error_Syntax : The function "needs_line_after" does not exist in "file.twig" at line 10

### ISSUE THREAD

**Issue by SebSept** [memio/memio#24]
Hi,

Thanks for this code generator, looks great.
This is my first try.

given this file : 

``` php
<?php

require 'vendor/autoload.php';

use Gnugat\Medio\Model\File as SourceFile;
use Gnugat\Medio\PrettyPrinter;

// make controller
$source = SourceFile::make('x/ChequeValidationModuleFrontController.php');

echo (new PrettyPrinter(
            new Twig_Environment(
                new Twig_Loader_Filesystem('vendor/gnugat/medio/templates/')
                )
            )
    )->generateCode($source);
```

I have the following error :

```
Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'The function "needs_line_after" does not exist in "file.twig" at line 10' in /x/vendor/twig/twig/lib/Twig/ExpressionParser.php:568
Stack trace:
#0 /x/vendor/twig/twig/lib/Twig/ExpressionParser.php(351): Twig_ExpressionParser->getFunctionNodeClass('needs_line_afte...', 10)
#1 /x/vendor/twig/twig/lib/Twig/ExpressionParser.php(144): Twig_ExpressionParser->getFunctionNode('needs_line_afte...', 10)
#2 /x/vendor/twig/twig/lib/Twig/ExpressionParser.php(84): Twig_ExpressionParser->parsePrimaryExpression()
#3 /x/vendor/twig/twig/lib/Twig/ExpressionParser.php(41): Twig_ExpressionParser->getPrimary()
#4 /x/vendor/twig/twig/lib/Twig/TokenParser/If.php(38): Twig_ExpressionParser->parseExpression()
#5 /home/seb/dev/htdocs/perso/p in /x/vendor/twig/twig/lib/Twig/ExpressionParser.php on line 568
```

is it a bug or is my prettyprinter badly constructed ?
By the way, there is no prettyprinter instantiation in the examples, you always use $prettyprinter.

**Comment by gnugat** [comment]
Hi @SebSept, I'm sorry you're experiencing this issue.
As described in the [Installation documentation](http://gnugat.github.io/medio/doc/02-installation.html) (section "Building the service"), you need to write the following:

``` php
<?php

require __DIR__.'/vendor/autoload.php';

use Gnugat\Medio\PrettyPrinter;
use Gnugat\Medio\TwigExtension\Line\ContractLineStrategy;
use Gnugat\Medio\TwigExtension\Line\FileLineStrategy;
use Gnugat\Medio\TwigExtension\Line\ObjectLineStrategy;
use Gnugat\Medio\TwigExtension\Phpdoc;
use Gnugat\Medio\TwigExtension\Type;
use Gnugat\Medio\TwigExtension\Whitespace;

$line = new Line();
$line->add(new ContractLineStrategy());
$line->add(new FileLineStrategy());
$line->add(new ObjectLineStrategy());

$loader = \Twig_Loader_Filesystem(__DIR__.'/vendor/gnugat/medio/templates/');
$twig = new \Twig_Environment($loader);
$twig->addExtension(new Phpdoc());
$twig->addExtension(new Type());
$twig->addExtension(new Whitespace());

$prettyPrinter = new PrettyPrinter($twig);
```

I know it seems a bit awkward, I'm planning on making the construction of PrettyPrinter much easier.
By the way, if you want you to avoid writing the relative path to the template, you can use Puli (follow the instruction in the [Installation documentation](http://gnugat.github.io/medio/doc/02-installation.html) , section "Puli: find the templates").

I hope this helps, I'll stay available for further questions.

**Comment by gnugat** [comment]
I'd like to apologize for the inconvenience, but the new version of Medio (1.0.0-alpha13) will break your code. You'll now need to write the following:

``` php
use Gnugat\Medio\Model\File as SourceFile;
use Gnugat\Medio\Model\Object;

// make controller
$source = SourceFile::make('x/ChequeValidationModuleFrontController.php', Object::make('ChequeValidationModuleFrontController'));

echo ($prettyPrinter->generateCode($source);
```

As you can see, you now need to give a second argument to `File`: an `Object` (to generate a class), or a `Contract` (to generate an interface).
I try to avoid breaking backward compatibility as much as possible, but Medio is still in an unstable version (alpha) and some early decisions I made need to be changed (for example before it was impossbile to generate interfaces).

**Comment by SebSept** [comment]
Yep,

Sorry, I missed the  "Building the service" doc, I apologize.

That's alpha version, so we should expect breaking changes, no problem ;).

Thanks for that concrete and fast answer :)

**Comment by gnugat** [comment]
Actually it's:

``` php
<?php

require __DIR__.'/vendor/autoload.php';

use Gnugat\Medio\PrettyPrinter;
use Gnugat\Medio\TwigExtension\Line\ContractLineStrategy;
use Gnugat\Medio\TwigExtension\Line\FileLineStrategy;
use Gnugat\Medio\TwigExtension\Line\ObjectLineStrategy;
use Gnugat\Medio\TwigExtension\Phpdoc;
use Gnugat\Medio\TwigExtension\Type;
use Gnugat\Medio\TwigExtension\Whitespace;

$line = new Line();
$line->add(new ContractLineStrategy());
$line->add(new FileLineStrategy());
$line->add(new ObjectLineStrategy());

$loader = \Twig_Loader_Filesystem(__DIR__.'/vendor/gnugat/medio/templates/');
$twig = new \Twig_Environment($loader);
$twig->addExtension(new Phpdoc());
$twig->addExtension(new Type());
$twig->addExtension(new Whitespace($line));

$prettyPrinter = new PrettyPrinter($twig);
```

Note the `$line` argument in `new Whitespace()`.
